### ISSUE TITLE
Add findIndex function to $

### ISSUE THREAD

**Issue by jonkoops** [Saartje87/pbjs-0.6#1]
---
### findIndex

Finds the index of an element in the set.
###### Signature

``` js
var someElement = PB.$('#element').find('.child')[0];
PB.$('#element').findIndex(someElement);
```
###### Arguments

{Mixed} - string, DOM node
###### Returns

{Number} - index of element or undefined

---

**Comment by jonkoops** [comment]
@Saartje87 Could you review my feature request?

**Comment by jonkoops** [comment]
Maybe '.findChildIndex' is a better name.

**Comment by Saartje87** [comment]
Use indexOf, usage ?

`PB.$$('*').indexOf( document.getElement('id') )`

`PB.$$('*').indexOf( PB.$('#id') )`

`PB.$$('*').indexOf( '#id' )`

**Comment by jonkoops** [comment]
## Okay, so this would be our spec?

### indexOf

Finds the index of an element in the set.

###### Signature

``` html
<div id="parent">
    <div id="one"></div>
    <div id="two"></div>
    <div id="three"></div>
</div>
```

``` js
PB.$('#parent').children().indexOf('#one'); // returns 0
PB.$('#parent').children().indexOf(PB.$('#two')); // returns 1
PB.$('#parent').children().indexOf(document.getElementById('#three')); // returns 2
PB.$('#parent').children().indexOf('#four'); // element not found, returns -1
```

###### Arguments

{Mixed} - string, DOM node, PBJS Node

###### Returns

{Number} - index of element or -1 if no element was found

---

**Comment by Saartje87** [comment]
Sounds great! Make sure the following typo wont be in the docs document.getElementById('#three') should be document.getElementById('three')  ;)

@Rapido3011 could you add it in the PB-$.md file ?
