### ISSUE TITLE
Touch gestures (plugin)

### ISSUE THREAD

**Issue by Saartje87** [Saartje87/pbjs-0.6#10]
Just an idea.

``` js
PB.$('#element').touch('tab', function ( e ) {});
PB.$('#element').touch('dbltab', function ( e ) {});
PB.$('#element').touch('press', function ( e ) {});
PB.$('#element').touch('rotate', function ( e ) {});
```

**Comment by RX01** [comment]
I like this idea.

Though, 'tab' and 'dbltab' should be renamed to 'tap' & 'dbltap', e.g.:

PB.$('#element').touch('tap', function ( e ) {});
PB.$('#element').touch('dbltap', function ( e ) {});

I would also suggest renaming 'press' to 'continuous' or 'hold', or differentiating between a 'press' and a 'hold'. Perhaps by adding a touch_length argument.

Also, one could imagine adding 'spread' and 'pinch' as touch events.

On multiple digits that touch the screen:
Should the number of digits that touch the screen be accounted for as a singular event?
Or should it be based on an additional argument signifying the number of digits activating the event as a number?

An example of a .touch method, including the number of digits and length of press:

  PB.$('#element').touch('press', function ( e ) {}, 200, 2); 
                                  (event, callback, length, number of digits)

Regards.

**Comment by jonkoops** [comment]
@Saartje87 Why is this enhancement marked `wontfix`?

**Comment by Saartje87** [comment]
This should be a plugin,  so a 'wontfix' for now.

**Comment by Saartje87** [comment]
Closing the issue :) Would be pretty cool to create a plugin for this sometime
