### ISSUE TITLE
PB.$.ready

### ISSUE THREAD

**Issue by Saartje87** [Saartje87/pbjs-0.6#12]
Add method to know when the DOM is ready to be touched

``` js
PB.$.ready(function () {

  // Ready to touch the DOM!
})
```

**Comment by jonkoops** [comment]
If this is a shim for the `DOMContentLoaded` event we should place this in [legacy.js](https://github.com/Saartje87/pbjs-0.6/blob/master/src/%24/legacy.js)

**Comment by Saartje87** [comment]
Implemented
