### ISSUE TITLE
PB.$.on expression proposal

### ISSUE THREAD

**Issue by Saartje87** [Saartje87/pbjs-0.6#14]
In event2.js I changed the second argument so we only get the callback triggered when the target or one of it's parents matches the selector, btw this is optional. 

Now the big question, when the event matches the target should we make event.currentTarget be '.ony-match-me' element or introduce a new event property that holds this element? 

Disadvantage , currentTarget is a readonly property, so we must create a clone of the event object..

example

``` js
PB.$('#element').on('click', '.ony-match-me', function ( e ) {

}, this);
```

**Comment by Saartje87** [comment]
After a short council we decided to add a new property, `e.selectorTarget`. When no css expression is given, selectorTarget will always return null.

Any further toughts about this?

@Rapido3011 @dennislaupman @RX01 

``` html
<ul id="element">
    <li></li>
    <li class="only-match-me"><span></span></li>
</ul>
```

Example

``` js
PB.$('#element').on('click', '.ony-match-me', function ( e ) {

    e.target; // <span></span>
    e.currentTarget; // <ul id="element"></ul>
    e.selectorTarget; // <li class="only-match-me"></li>
}, this);
```

**Comment by jonkoops** [comment]
So the event will only be triggered when a child that matches the given selector is clicked?

**Comment by Saartje87** [comment]
Yes in the above example only second li will trigger the event. In this case `currentTarget` will be the element `li.only-match-me`, cause selectorTarget is removed.

I guess it's a good thing to remove selectorTarget, so no code modifaction is needed when adding or removing the selector arguments.

**Comment by jonkoops** [comment]
It seems `selectorTarget` is indeed unnecessary weight.
