### ISSUE TITLE
Rename morph to transition(?)

### ISSUE THREAD

**Issue by Saartje87** [Saartje87/pbjs-0.6#25]
Any toughts?

**Comment by jonkoops** [comment]
Or animate. We should make a draft for the new animation function.

**Comment by Saartje87** [comment]
Animations could be seen as more complex (keyframes etc).

Transition is more what the current method handles just go from point a to b with given properties, duration.. Thats my tought about it ;) Still can convince me to use animate?:P

**Comment by desjob** [comment]
an animation is a transition, but a transition doesnt have to be an animation. i say go with transition!

**Comment by dennislaupman** [comment]
Transition +1, good substantiation! Job

**Comment by jonkoops** [comment]
I agree with @desjob and @Saartje87, a transtion is a part of an animation. So the logical thing to do would be to rename `morph` to `transition` and maybe add an `animate` function for advanced animations and timing functions in the future. What's your opinion on this guys?

**Comment by Saartje87** [comment]
Sounds great!

**Comment by jonkoops** [comment]
Could someone review my proposal for the new `$.transition` function? see #7

**Comment by Saartje87** [comment]
Closing this issue, added transition (morph is a reference to transition)
