### ISSUE TITLE
Add better CSS transforms support

### ISSUE THREAD

**Issue by jonkoops** [Saartje87/pbjs-0.6#27]
## $.getTransform

Gets a specific transformation value by name.
### Usage

``` html
<div id="example" style="transform: rotate(90deg);"></div>
```

``` js
PB.$$('#example').getTransform('rotation'); // 1.57079633
```
#### name (String) required

Specifies the transform to get. Any of the following options are valid:
- rotation
- translationX
- translationY
- translationZ
- scaleX
- scaleY
- scaleZ
- skewX
- skewY

**Comment by Saartje87** [comment]
Another proposal

``` js
PB.$('#element').setStyle({

    x: -10,
    y: 0,
    z: 100,
    scale: '90deg'
});

PB.$('#element').getStyle('scale'); // Return 90deg ?
```

**Comment by jonkoops** [comment]
@Saartje87 I think we should consider all properties passed into setStyle as reserved. Maybe passing a transform Object into the setStyle method?

``` js
PB.$('#element').setStyle({

    transform: {
        scale: .5,
        rotate: '90deg',
        translateX: 20,
        translateY: '50%'
    }
});
```

This way we could also make the return value of the .getStyle('transform') method that same object.
