### ISSUE TITLE
Remove PB.$$

### ISSUE THREAD

**Issue by Saartje87** [Saartje87/pbjs-0.6#28]
I think we should reconsider PB.$$, it's to much confusion it does not have the same input as PB.$ and the ideology does not work, programmers should use PB.$ as much as possible but instead we see more usage of PB.$$ then PB.$.. 

So in the dev branch I added a message to PB.$$ as a warning and added the PB.$$ functionality to PB.$.

**Comment by jonkoops** [comment]
@Saartje87 
![ClapClap](http://www.reactiongifs.com/wp-content/uploads/2012/09/slow-clap-gif.gif)

**Comment by Saartje87** [comment]
:D
